#!/usr/bin/env bash
#
# Najva Messenger — one-shot installer for Ubuntu 24.04.
#
#   curl -fsSL https://raw.githubusercontent.com/MatinMHF/najva-messenger/main/install.sh | sudo bash
#
# Asks for ports, admin credentials and a domain, issues a Let's Encrypt
# certificate if you have one, or generates a self-signed Root CA certificate
# with a public download link so camera/mic/voice/video work out-of-the-box.
set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/MatinMHF/najva-messenger.git}"
INSTALL_DIR="${INSTALL_DIR:-/opt/najva}"

bold() { printf '\033[1m%s\033[0m\n' "$*"; }
info() { printf '  %s\n' "$*"; }
warn() { printf '\033[33m  ! %s\033[0m\n' "$*"; }
die()  { printf '\033[31m  x %s\033[0m\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "Run as root (sudo bash install.sh)."

# -------------------------------------------------------- existing installation

if [ -d "$INSTALL_DIR/.git" ] && [ -f "$INSTALL_DIR/.env" ] && [ -x /usr/local/bin/najva ]; then
  cd "$INSTALL_DIR"
  . "$INSTALL_DIR/scripts/najva-lib.sh"

  CURRENT="$(installed_version)"
  LATEST="$(latest_version || true)"

  if [ -n "$LATEST" ] && version_gt "$LATEST" "$CURRENT"; then
    bold "Najva $CURRENT is installed at $INSTALL_DIR; version $LATEST is available."
    read -rp "  Do you want to update? [y/N] " ANSWER </dev/tty
    case "$ANSWER" in
      y|Y) perform_update; exit $? ;;
      *)   info "Left unchanged. Run 'najva' to manage it."; exit 0 ;;
    esac
  fi

  bold "You already have it installed."
  info "Version $CURRENT at $INSTALL_DIR."
  if [ -z "$LATEST" ]; then
    warn "Could not check for a newer version. Is the server online?"
  else
    info "Already up to date."
  fi
  info "Run 'najva' to manage it."
  exit 0
fi

# ----------------------------------------------------------------- dependencies

bold "==> Installing dependencies"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq curl git openssl ca-certificates certbot >/dev/null

if ! command -v docker >/dev/null; then
  info "Installing Docker Engine..."
  curl -fsSL https://get.docker.com | sh >/dev/null
fi
docker compose version >/dev/null 2>&1 || die "Docker Compose plugin missing."
info "Docker $(docker --version | awk '{print $3}' | tr -d ,)"

# ---------------------------------------------------------------------- source

bold "==> Fetching Najva"
if [ -d "$INSTALL_DIR/.git" ]; then
  git -C "$INSTALL_DIR" pull --ff-only >/dev/null
  info "Updated $INSTALL_DIR"
else
  git clone --depth 1 "$REPO_URL" "$INSTALL_DIR" >/dev/null 2>&1
  info "Cloned into $INSTALL_DIR"
fi
cd "$INSTALL_DIR"

# Shared config/cert helpers, also used by the `najva` management menu.
. "$INSTALL_DIR/scripts/najva-lib.sh"

# ------------------------------------------------------------------- questions

bold "==> Configuration"

if [ -f .env ] && grep -q '^ADMIN_USERNAME=' .env && grep -q '^NAJVA_HTTP_PORT=' .env; then
  load_env
  ADMIN_USERNAME="$(grep '^ADMIN_USERNAME=' .env | cut -d= -f2-)"
  PUBLIC_IP="$(grep '^MEDIASOUP_ANNOUNCED_IP=' .env | cut -d= -f2-)"
  info "Reusing the answers already in $INSTALL_DIR/.env"
  info "Admin '$ADMIN_USERNAME', ports $HTTP_PORT/$HTTPS_PORT, domain ${DOMAIN:-<none>}"
  info "Run 'najva' to change any of them."
else
  read -rp "  HTTP port  [80]: " HTTP_PORT </dev/tty
  HTTP_PORT="${HTTP_PORT:-80}"
  read -rp "  HTTPS port [443]: " HTTPS_PORT </dev/tty
  HTTPS_PORT="${HTTPS_PORT:-443}"

  while :; do
    read -rp "  Admin username [admin]: " ADMIN_USERNAME </dev/tty
    ADMIN_USERNAME="${ADMIN_USERNAME:-admin}"
    read -rsp "  Admin password (min 8 chars): " ADMIN_PASSWORD </dev/tty; echo
    read -rsp "  Confirm password: " ADMIN_PASSWORD2 </dev/tty; echo
    [ "$ADMIN_PASSWORD" = "$ADMIN_PASSWORD2" ] || { warn "Passwords do not match."; continue; }
    [ "${#ADMIN_PASSWORD}" -ge 8 ] || { warn "Password too short."; continue; }
    break
  done

  echo
  info "Enter your domain, or leave blank if you don't have one."
  read -rp "  What is your domain? []: " DOMAIN </dev/tty
  DOMAIN="${DOMAIN:-}"

  if [ -n "$DOMAIN" ]; then
    read -rp "  Email for Let's Encrypt notices [admin@$DOMAIN]: " LE_EMAIL </dev/tty
    LE_EMAIL="${LE_EMAIL:-admin@$DOMAIN}"
  else
    LE_EMAIL=""
  fi

  PUBLIC_IP="$(curl -fsS4 https://ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}')"
  HOSTNAME_="${DOMAIN:-$PUBLIC_IP}"

  bold "==> Writing configuration"
  rand() { openssl rand -hex 32; }

  if [ -f .env ]; then
    cp .env ".env.bak.$(date +%s)"
    info "Existing .env backed up"
  fi

  DB_PASSWORD="$(rand)"
  cat > .env <<EOF
# Generated by install.sh on $(date -Iseconds). Secrets are random per install.
NODE_ENV=production
PORT=3000

POSTGRES_USER=najva
POSTGRES_PASSWORD=$DB_PASSWORD
POSTGRES_DB=najva
DATABASE_URL=postgresql://najva:$DB_PASSWORD@postgres:5432/najva
REDIS_URL=redis://redis:6379

JWT_SECRET=$(rand)
JWT_REFRESH_SECRET=$(rand)
SERVER_SECRET=$(rand)
MEDIA_JWT_SECRET=$(rand)
TURN_SECRET=$(rand)

UPLOAD_DIR=/app/uploads
MAX_FILE_SIZE=104857600

NAJVA_DOMAIN=$DOMAIN
NAJVA_HTTP_PORT=$HTTP_PORT
NAJVA_HTTPS_PORT=$HTTPS_PORT
CORS_ORIGIN=__PUBLIC_URL__

WEBAUTHN_RP_ID=$HOSTNAME_
WEBAUTHN_RP_NAME=Najva
WEBAUTHN_ORIGIN=__PUBLIC_URL__

STUN_URLS=stun:stun.l.google.com:19302
TURN_URLS=turn:$HOSTNAME_:3478
MEDIASOUP_ANNOUNCED_IP=$PUBLIC_IP
MEDIA_SERVER_PUBLIC_URL=__PUBLIC_URL__

VAPID_SUBJECT=mailto:${LE_EMAIL:-admin@$HOSTNAME_}

ADMIN_USERNAME=$ADMIN_USERNAME
ADMIN_PASSWORD=$ADMIN_PASSWORD
EOF
  chmod 600 .env
fi

write_static_config

TLS=no
if [ -n "$DOMAIN" ]; then
  bold "==> Requesting Let's Encrypt certificate for $DOMAIN"
  if [ "$HTTP_PORT" != "80" ]; then
    warn "Let's Encrypt validates over port 80; HTTP port is $HTTP_PORT."
  fi
  if issue_certificate; then
    TLS=letsencrypt
    info "Certificate installed."
    mkdir -p /etc/letsencrypt/renewal-hooks/deploy
    printf '#!/bin/sh\ncd %s && docker compose exec -T nginx nginx -s reload\n' "$INSTALL_DIR" \
      > /etc/letsencrypt/renewal-hooks/deploy/najva.sh
    chmod +x /etc/letsencrypt/renewal-hooks/deploy/najva.sh
  else
    warn "Let's Encrypt certificate issuance failed. Falling back to self-signed Root CA certificate."
    generate_self_signed_cert
    TLS=selfsigned
  fi
else
  info "No domain given — generating self-signed Root CA certificate for IP $PUBLIC_IP."
  generate_self_signed_cert
  TLS=selfsigned
fi

write_nginx_conf "$TLS"
if [ "$TLS" = "letsencrypt" ] || [ "$TLS" = "selfsigned" ]; then
  apply_urls https "$HTTPS_PORT"
else
  apply_urls http "$HTTP_PORT"
fi

# ---------------------------------------------------------------------- launch

bold "==> Building and starting (this takes a few minutes)"
docker compose build >/dev/null
docker compose up -d

info "Waiting for the API to come up..."
for _ in $(seq 1 60); do
  docker compose exec -T server node -e 'process.exit(0)' </dev/null >/dev/null 2>&1 && break
  sleep 2
done

if ! grep -q '^VAPID_PUBLIC_KEY=' .env; then
  bold "==> Generating push notification keys"
  KEYS="$(docker compose exec -T server node -e \
    'const k=require("web-push").generateVAPIDKeys();console.log(k.publicKey+" "+k.privateKey)' </dev/null 2>/dev/null || true)"
  if [ -n "$KEYS" ]; then
    printf 'VAPID_PUBLIC_KEY=%s\nVAPID_PRIVATE_KEY=%s\n' ${KEYS} >> .env
    docker compose up -d server >/dev/null
    info "Push keys generated."
  else
    warn "Could not generate VAPID keys; push notifications stay disabled."
  fi
fi

bold "==> Creating the admin account"
if SEED_OUT="$(docker compose exec -T server npm run seed </dev/null 2>&1)"; then
  info "Admin '$ADMIN_USERNAME' created."
else
  warn "Seeding failed — run 'najva' and pick 'Reset admin credentials'."
  printf '%s\n' "$SEED_OUT" | tail -5
fi

install -m 755 scripts/najva.sh /usr/local/bin/najva
printf 'INSTALL_DIR=%s\n' "$INSTALL_DIR" > /etc/najva.conf

APP_URL="$(grep '^CORS_ORIGIN=' .env | cut -d= -f2)"

echo
bold "Najva is up."
info "App URL:         $APP_URL"
info "Admin Panel:     $APP_URL/admin"
info "Admin User:      $ADMIN_USERNAME"
if [ "$TLS" = "selfsigned" ]; then
  info "CA Certificate:  http://$HOSTNAME_/ca.crt"
  info "(Download 'najva-ca.crt' and install it into Trusted Root Authorities for camera/mic access)"
fi
info "Manage:          run 'najva'"
