#!/usr/bin/env bash
# Shared helpers for install.sh and the `najva` management menu.
# Expects DOMAIN, HOSTNAME_, LE_EMAIL, HTTP_PORT, HTTPS_PORT and cwd = install dir.

bold() { printf '[1m%s[0m
' "$*"; }
info() { printf '  %s
' "$*"; }
warn() { printf '[33m  ! %s[0m
' "$*"; }

# The public URL depends on whether TLS ends up working, so it is stamped in
# later by apply_urls() rather than guessed here.
apply_urls() {
  local scheme="$1" port="$2" url
  url="$scheme://$HOSTNAME_"
  if { [ "$scheme" = "http" ] && [ "$port" != "80" ]; } ||
     { [ "$scheme" = "https" ] && [ "$port" != "443" ]; }; then
    url="$url:$port"
  fi
  sed -i "s#__PUBLIC_URL__#$url#g; s#^CORS_ORIGIN=.*#CORS_ORIGIN=$url#; \
           s#^WEBAUTHN_ORIGIN=.*#WEBAUTHN_ORIGIN=$url#; \
           s#^MEDIA_SERVER_PUBLIC_URL=.*#MEDIA_SERVER_PUBLIC_URL=$url#" .env
  info "Public URL: $url"
}

# Stamps the install-time answers into the files Docker mounts: coturn shares
# TURN_SECRET with the API server, and the override carries the host ports.
write_static_config() {
  # coturn shares TURN_SECRET with the API server and needs the real realm.
  TURN_SECRET_VALUE="$(grep '^TURN_SECRET=' .env | cut -d= -f2)"
  sed -i "s#^realm=.*#realm=$HOSTNAME_#; s#^static-auth-secret=.*#static-auth-secret=$TURN_SECRET_VALUE#" \
    turn/turnserver.conf

  cat > docker-compose.override.yml <<EOF
# Generated by install.sh — host port mapping and certificate mounts.
services:
  nginx:
    ports:
      - "$HTTP_PORT:80"
      - "$HTTPS_PORT:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
EOF
}

# ---------------------------------------------------------------- nginx

# Regenerates nginx.conf for the current certificate state. Called again by the
# `najva` menu after a retried certificate issuance, so it must stay idempotent.
write_nginx_conf() {
  local tls="$1" cert_dir="/etc/letsencrypt/live/$DOMAIN"
  local locations
  locations=$(cat <<'LOC'
        location /api/files/ {
            limit_req zone=files_limit burst=200 nodelay;
            proxy_pass http://server:3000;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 90s;
            client_max_body_size 100M;
        }

        location /api/ {
            limit_req zone=api_limit burst=20 nodelay;
            proxy_pass http://server:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 90s;
        }

        location /socket.io/ {
            proxy_pass http://server:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 86400s;
            proxy_send_timeout 86400s;
        }

        location / {
            proxy_pass http://client:80;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;

            location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
                proxy_pass http://client:80;
                expires 30d;
                add_header Cache-Control "public, no-transform";
            }
        }
LOC
)

  {
    cat <<'HEAD'
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    client_max_body_size 100M;

    gzip on;
    gzip_disable "msie6";
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;
    limit_req_zone $binary_remote_addr zone=files_limit:10m rate=100r/s;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header X-XSS-Protection "1; mode=block";
HEAD

    if [ "$tls" = "yes" ]; then
      cat <<HTTPS
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    server {
        listen 80;
        server_name $DOMAIN;
        location /.well-known/acme-challenge/ { root /var/www/certbot; }
        location / { return 301 https://\$host\$request_uri; }
    }

    server {
        listen 443 ssl;
        http2 on;
        server_name $DOMAIN;

        ssl_certificate     $cert_dir/fullchain.pem;
        ssl_certificate_key $cert_dir/privkey.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers off;
        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 1d;

$locations
    }
}
HTTPS
    else
      cat <<PLAIN

    server {
        listen 80;
        server_name _;

$locations
    }
}
PLAIN
    fi
  } > nginx/nginx.conf
}

# ---------------------------------------------------------------- certificate

# Issues a certificate with certbot standalone on port 80. Port 80 must be free,
# so anything already bound there (including our own nginx) is stopped first.
issue_certificate() {
  [ -n "$DOMAIN" ] || return 1
  docker compose stop nginx >/dev/null 2>&1 || true
  certbot certonly --standalone --non-interactive --agree-tos \
    --email "$LE_EMAIL" -d "$DOMAIN" --keep-until-expiring
}

# ---------------------------------------------------------------- environment

# The answers given at install time live in .env; re-read them before every
# action so the menu keeps working after a domain or port change. Expects
# cwd = install dir.
load_env() {
  DOMAIN="$(grep '^NAJVA_DOMAIN=' .env | cut -d= -f2-)"
  HTTP_PORT="$(grep '^NAJVA_HTTP_PORT=' .env | cut -d= -f2-)"
  HTTPS_PORT="$(grep '^NAJVA_HTTPS_PORT=' .env | cut -d= -f2-)"
  LE_EMAIL="$(grep '^VAPID_SUBJECT=' .env | cut -d: -f2-)"
  HOSTNAME_="${DOMAIN:-$(hostname -I | awk '{print $1}')}"
  [ -n "$DOMAIN" ] && [ -d "/etc/letsencrypt/live/$DOMAIN" ] && TLS=yes || TLS=no
}

# ---------------------------------------------------------------- versioning

# Branch the install tracks. Overridable so a fork or a test install can follow
# something other than main.
NAJVA_BRANCH="${NAJVA_BRANCH:-main}"

# Version of the checkout in $1 (default: cwd). Installs made before VERSION
# existed have no file, and must sort below every real release.
installed_version() {
  local dir="${1:-.}"
  if [ -r "$dir/VERSION" ]; then
    tr -d ' \t\r\n' < "$dir/VERSION"
  else
    printf '0.0.0'
  fi
}

# Version on the tracked branch. Needs the network: returns non-zero and prints
# nothing when the fetch fails, so callers can tell "no update available" apart
# from "could not check".
latest_version() {
  local dir="${1:-.}"
  command -v git >/dev/null || return 1
  git -C "$dir" fetch --quiet origin "$NAJVA_BRANCH" 2>/dev/null || return 1
  git -C "$dir" show "origin/$NAJVA_BRANCH:VERSION" 2>/dev/null | tr -d ' \t\r\n'
}

# True when $1 is strictly newer than $2. sort -V understands 1.10.0 > 1.9.0,
# which a plain string compare gets wrong.
version_gt() {
  [ "$1" != "$2" ] && [ "$(printf '%s\n%s\n' "$1" "$2" | sort -V | tail -1)" = "$1" ]
}

# Fast-forwards the checkout to the tracked branch and restarts the stack.
# Expects cwd = install dir. Returns non-zero if the update could not be applied.
perform_update() {
  local from to
  from="$(installed_version)"

  bold "==> Updating Najva"
  git fetch --quiet origin "$NAJVA_BRANCH" 2>/dev/null \
    || { warn "Could not reach the repository."; return 1; }
  git reset --hard "origin/$NAJVA_BRANCH" >/dev/null 2>&1 \
    || { warn "Could not apply the update. Check 'git -C $PWD status'."; return 1; }
  to="$(installed_version)"

  # .env is gitignored so the secrets survive the reset, but nginx.conf and
  # turnserver.conf are tracked — the reset just threw away the install-time
  # answers stamped into them, so put them back before anything restarts.
  load_env
  write_static_config
  write_nginx_conf "$TLS"
  if [ "$TLS" = yes ]; then apply_urls https "$HTTPS_PORT"; else apply_urls http "$HTTP_PORT"; fi

  info "Rebuilding containers (this takes a few minutes)..."
  docker compose build >/dev/null
  docker compose up -d

  # The menu script is copied to /usr/local/bin at install time, so a changed
  # copy in the repo only takes effect once it is reinstalled.
  install -m 755 scripts/najva.sh /usr/local/bin/najva

  info "Updated $from -> $to"
}

