#!/usr/bin/env bash
# Shared helpers for install.sh and the `najva` management menu.
# Expects DOMAIN, HOSTNAME_, LE_EMAIL, HTTP_PORT, HTTPS_PORT and cwd = install dir.

bold() { printf '\033[1m%s\033[0m\n' "$*"; }
info() { printf '  %s\n' "$*"; }
warn() { printf '\033[33m  ! %s\033[0m\n' "$*"; }

apply_urls() {
  local scheme="$1" port="$2" url
  url="$scheme://$HOSTNAME_"
  if { [ "$scheme" = "http" ] && [ "$port" != "80" ]; } || \
     { [ "$scheme" = "https" ] && [ "$port" != "443" ]; }; then
    url="$url:$port"
  fi
  sed -i "s#^CORS_ORIGIN=.*#CORS_ORIGIN=$url#; \
          s#^WEBAUTHN_ORIGIN=.*#WEBAUTHN_ORIGIN=$url#; \
          s#^MEDIA_SERVER_PUBLIC_URL=.*#MEDIA_SERVER_PUBLIC_URL=$url#" .env
  info "Public URL: $url"
}

generate_self_signed_cert() {
  local target_ip target_host
  target_ip="${PUBLIC_IP:-$(curl -fsS4 https://ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}')}"
  target_host="${DOMAIN:-$target_ip}"

  mkdir -p certs

  if [ ! -f certs/najva-ca.key ] || [ ! -f certs/najva-ca.crt ]; then
    bold "==> Generating Najva Root CA certificate"
    openssl req -x509 -new -nodes \
      -keyout certs/najva-ca.key \
      -out certs/najva-ca.crt \
      -days 3650 \
      -subj "/CN=Najva Root CA ($target_host)/O=Najva Messenger/OU=Security" >/dev/null 2>&1
  fi

  cat > certs/server_ext.cnf <<EOF
[req]
distinguished_name = req_distinguished_name
req_extensions = v3_req
prompt = no

[req_distinguished_name]
CN = $target_host
O = Najva Messenger

[v3_req]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[alt_names]
DNS.1 = localhost
DNS.2 = $target_host
IP.1 = 127.0.0.1
IP.2 = $target_ip
EOF

  openssl req -new -nodes \
    -keyout certs/najva-server.key \
    -out certs/najva-server.csr \
    -config certs/server_ext.cnf >/dev/null 2>&1

  openssl x509 -req \
    -in certs/najva-server.csr \
    -CA certs/najva-ca.crt \
    -CAkey certs/najva-ca.key \
    -CAcreateserial \
    -out certs/najva-server.crt \
    -days 3650 \
    -extfile certs/server_ext.cnf \
    -extensions v3_req >/dev/null 2>&1

  chmod 644 certs/najva-ca.crt certs/najva-server.crt
  chmod 600 certs/najva-ca.key certs/najva-server.key
  info "Self-signed certificate generated for $target_ip"
}

write_static_config() {
  mkdir -p certs
  TURN_SECRET_VALUE="$(grep '^TURN_SECRET=' .env | cut -d= -f2-)"
  sed -i "s#^realm=.*#realm=$HOSTNAME_#; s#^static-auth-secret=.*#static-auth-secret=$TURN_SECRET_VALUE#" \
    turn/turnserver.conf

  PUBLIC_IP="${PUBLIC_IP:-$(curl -fsS4 https://ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}')}"
  sed -i '/^external-ip=/d' turn/turnserver.conf
  if [ -n "$PUBLIC_IP" ]; then
    printf 'external-ip=%s\n' "$PUBLIC_IP" >> turn/turnserver.conf
    info "TURN external address: $PUBLIC_IP"
  else
    warn "Could not determine public IP; leaving external-ip unset."
  fi

  cat > docker-compose.override.yml <<EOF
# Generated by install.sh — host port mapping and certificate mounts.
services:
  nginx:
    ports:
      - "$HTTP_PORT:80"
      - "$HTTPS_PORT:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
EOF
}

write_nginx_conf() {
  local tls="$1" cert_dir=""
  if [ "$tls" = "letsencrypt" ]; then
    cert_dir="/etc/letsencrypt/live/$DOMAIN"
  elif [ "$tls" = "selfsigned" ]; then
    cert_dir="/etc/nginx/certs"
  fi

  local locations
  locations=$(cat <<'LOC'
        location /ca.crt {
            alias /etc/nginx/certs/najva-ca.crt;
            default_type application/x-x509-ca-cert;
            add_header Content-Disposition 'attachment; filename="najva-ca.crt"';
        }

        location /api/files/ {
            limit_req zone=files_limit burst=200 nodelay;
            proxy_pass http://server:3000;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 90s;
            client_max_body_size 100M;
        }

        location /api/ {
            limit_req zone=api_limit burst=20 nodelay;
            proxy_pass http://server:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 90s;
        }

        location /socket.io/ {
            proxy_pass http://server:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 86400s;
            proxy_send_timeout 86400s;
        }

        location / {
            proxy_pass http://client:80;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;

            location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
                proxy_pass http://client:80;
                expires 30d;
                add_header Cache-Control "public, no-transform";
            }
        }
LOC
)

  {
    cat <<'HEAD'
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    client_max_body_size 100M;

    gzip on;
    gzip_disable "msie6";
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;
    limit_req_zone $binary_remote_addr zone=files_limit:10m rate=100r/s;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header X-XSS-Protection "1; mode=block";
HEAD

    if [ "$tls" = "letsencrypt" ]; then
      cat <<HTTPS
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    server {
        listen 80;
        server_name $DOMAIN;
        location /.well-known/acme-challenge/ { root /var/www/certbot; }
        location /ca.crt {
            alias /etc/nginx/certs/najva-ca.crt;
            default_type application/x-x509-ca-cert;
            add_header Content-Disposition 'attachment; filename="najva-ca.crt"';
        }
        location / { return 301 https://\$host\$request_uri; }
    }

    server {
        listen 443 ssl;
        http2 on;
        server_name $DOMAIN;

        ssl_certificate     $cert_dir/fullchain.pem;
        ssl_certificate_key $cert_dir/privkey.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers off;
        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 1d;

$locations
    }
}
HTTPS
    elif [ "$tls" = "selfsigned" ]; then
      cat <<SELFSIGNED
    server {
        listen 80;
        server_name _;
        location /ca.crt {
            alias /etc/nginx/certs/najva-ca.crt;
            default_type application/x-x509-ca-cert;
            add_header Content-Disposition 'attachment; filename="najva-ca.crt"';
        }
        location / { return 301 https://\$host\$request_uri; }
    }

    server {
        listen 443 ssl;
        http2 on;
        server_name _;

        ssl_certificate     /etc/nginx/certs/najva-server.crt;
        ssl_certificate_key /etc/nginx/certs/najva-server.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers off;
        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 1d;

$locations
    }
}
SELFSIGNED
    else
      cat <<PLAIN

    server {
        listen 80;
        server_name _;

$locations
    }
}
PLAIN
    fi
  } > nginx/nginx.conf
}

issue_certificate() {
  [ -n "$DOMAIN" ] || return 1
  docker compose stop nginx >/dev/null 2>&1 || true
  certbot certonly --standalone --non-interactive --agree-tos \
    --email "$LE_EMAIL" -d "$DOMAIN" --keep-until-expiring
}

load_env() {
  DOMAIN="$(grep '^NAJVA_DOMAIN=' .env | cut -d= -f2-)"
  HTTP_PORT="$(grep '^NAJVA_HTTP_PORT=' .env | cut -d= -f2-)"
  HTTPS_PORT="$(grep '^NAJVA_HTTPS_PORT=' .env | cut -d= -f2-)"
  LE_EMAIL="$(grep '^VAPID_SUBJECT=' .env | cut -d: -f2-)"
  PUBLIC_IP="$(grep '^MEDIASOUP_ANNOUNCED_IP=' .env | cut -d= -f2-)"
  HOSTNAME_="${DOMAIN:-$PUBLIC_IP}"
  if [ -n "$DOMAIN" ] && [ -d "/etc/letsencrypt/live/$DOMAIN" ]; then
    TLS=letsencrypt
  elif [ -f "certs/najva-server.crt" ]; then
    TLS=selfsigned
  else
    TLS=no
  fi
}

NAJVA_BRANCH="${NAJVA_BRANCH:-main}"

installed_version() {
  local dir="${1:-.}"
  if [ -r "$dir/VERSION" ]; then
    tr -d ' \t\r\n' < "$dir/VERSION"
  else
    printf '0.0.0'
  fi
}

latest_version() {
  local dir="${1:-.}"
  command -v git >/dev/null || return 1
  git -C "$dir" fetch --quiet origin "$NAJVA_BRANCH" 2>/dev/null || return 1
  git -C "$dir" show "origin/$NAJVA_BRANCH:VERSION" 2>/dev/null | tr -d ' \t\r\n'
}

version_gt() {
  [ "$1" != "$2" ] && [ "$(printf '%s\n%s\n' "$1" "$2" | sort -V | tail -1)" = "$1" ]
}

perform_update() {
  local from to
  from="$(installed_version)"

  bold "==> Updating Najva"
  git fetch --quiet origin "$NAJVA_BRANCH" 2>/dev/null \
    || { warn "Could not reach the repository."; return 1; }
  git reset --hard "origin/$NAJVA_BRANCH" >/dev/null 2>&1 \
    || { warn "Could not apply the update. Check 'git -C $PWD status'."; return 1; }
  to="$(installed_version)"

  load_env
  write_static_config
  write_nginx_conf "$TLS"
  if [ "$TLS" = "letsencrypt" ] || [ "$TLS" = "selfsigned" ]; then
    apply_urls https "$HTTPS_PORT"
  else
    apply_urls http "$HTTP_PORT"
  fi

  info "Rebuilding containers (this takes a few minutes)..."
  docker compose build >/dev/null
  docker compose up -d

  install -m 755 scripts/najva.sh /usr/local/bin/najva
  info "Updated $from -> $to"
}
